apiVersion: v1
kind: Namespace
metadata:
  name: demoreqrespj
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ssl-issuer
spec:
  ca:
    secretName: ca-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demoreqrespj-deploy
  namespace: demoreqrespj
spec:
  replicas: 4
  selector:
    matchLabels: 
      app: demoreqrespj
  template:
    metadata:
      labels:
        app: demoreqrespj
    spec:
      containers:
      - name: demoreqrespj
        image: mkubik/demoreqrespj:0.1.4
        ports:
        - name: web
          containerPort: 8080
          containerPort: 9090
        livenessProbe:
          httpGet:
            path: /health/liveness
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health/readiness
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: demoreqrespj-svc
  namespace: demoreqrespj
  labels:
    app: demoreqrespj
spec:
  type: ClusterIP
  ports:
  - name:  http
    port:  8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: demoreqrespj
---
apiVersion: v1
kind: Service
metadata:
  name: demoreqrespj-actuator
  namespace: demoreqrespj
  labels:
    app: demoreqrespj
spec:
  type: ClusterIP
  ports:
  - name:  http
    port:  9090
    targetPort: 9090
    protocol: TCP
  selector:
    app: demoreqrespj
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demoreqrespj-ingress
  namespace: demoreqrespj
spec:
  rules:
  - host: "demoreqrespj.kubik-hq.home"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: app-test-1-svc 
            port:
              number: 80
  tls:
  - hosts:
    - demoreqrespj.kubik-hq.home
    secretName: ca-secret              
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: selfsigned-cert
  namespace: demoreqrespj
spec:
  secretName: ca-secret
  issuerRef:
    name: ssl-issuer
    kind: ClusterIssuer
  dnsNames:
    - demoreqrespj.kubik-hq.home
