apiVersion: v1
kind: Namespace
metadata:
  name: demoreqrespj
---
apiVersion: v1
kind: Secret
metadata:
  name: demoreqrespj-tls-secret
  namespace: demoreqrespj
type: Opaque
data:
  tls.cert: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZ4ekNDQTYrZ0F3SUJBZ0lVU1NIeE1mM3lvamRaaWhzWG9DWUNyR1ZCbHJrd0RRWUpLb1pJaHZjTkFRRUwKQlFBd2N6RUxNQWtHQTFVRUJoTUNSRVV4RXpBUkJnTlZCQWdNQ2xOdmJXVXRVM1JoZEdVeElUQWZCZ05WQkFvTQpHRWx1ZEdWeWJtVjBJRmRwWkdkcGRITWdVSFI1SUV4MFpERXNNQ29HQTFVRUF3d2paR1Z0YjNKbGNYSmxjM0JxCkxtdDFZbVV0WkdWdGJ5MHhMbXQxWW1sckxtaHZiV1V3SGhjTk1qTXdPVEV6TVRFd01ESTFXaGNOTWpRd09URXkKTVRFd01ESTFXakJ6TVFzd0NRWURWUVFHRXdKRVJURVRNQkVHQTFVRUNBd0tVMjl0WlMxVGRHRjBaVEVoTUI4RwpBMVVFQ2d3WVNXNTBaWEp1WlhRZ1YybGtaMmwwY3lCUWRIa2dUSFJrTVN3d0tnWURWUVFERENOa1pXMXZjbVZ4CmNtVnpjR291YTNWaVpTMWtaVzF2TFRFdWEzVmlhV3N1YUc5dFpUQ0NBaUl3RFFZSktvWklodmNOQVFFQkJRQUQKZ2dJUEFEQ0NBZ29DZ2dJQkFLNVZreE16NlM1Zllsc2UvTVB3QzU4NEZFNUdXYWZiYVYrS2U2Nyswc2ZBNUVVdwpER2tJTnk5NDV4ZUd1WU1zYXMzVlB1WnE2ZmxHdTNEWmNJekV2KzVPdXNZM3AwdGxrS05hWnhBUktIYkIvYjV5CjJJU0phT0QwZkJqa0gzZEhBNFFQbXl0NGVIZWNMMlBYeEh3SE83b29XY01CekxITUJGaVpzY09iQ0k5Tzd6ZzEKUE5HSWV3QkNwdWMrUEh2cUpwSDdSWC9ZY2FMY01rbS9sTnZTT1EwUEEvODk2YjRGcm4rcSt3SFdsbi9MZGRKUAozTFBRT0pWdjRiL0ZmZ1gvV3c3QmRBVTFtOUxleERXUFBTUGxaOEx2UzkyNjlhTDFCSCtYTVNKT0ZuREVVTFZQCjA5Q1NDVkI0OEtyd3hPc2VoR1ZaZFFNQ2VWT0xITmxId0VRbFovTVVFU1hjaXFBVXFBald4UWVybGhtUnMwcXEKaHQ5aUczb1RpOFFUc1krOHBtdVdIVitsQ2JEaU45UmxZZTBkVStSTHZ6UmgxUGdORlk4cVRMVnA0Rkh4S1BkegpISGM1QnN2c0JBdmYyNmcwcDNZNkx5TEgxZmJCQmN1RlZ0S3Rrd0hYdGNmY1p5L2hxV252QlBmaUFLZHVpVWtHCjBhVWNOT3BoRTdueU45cGE0aXdVTjhhTXV5aFdFdmpvZ0c1NHlZV1M2UE5YTExKZnJhZkRnNVNhUU9YQ2xtZlAKMXdCYVowOG1jbjc1dU01am1Xc3NkSTVMTndhbmlhZUx0Z0h5ZVFMeVJ0NnhZSWZETFVCcG5DbFdtWnFZQUJBQgpTb2V5bnpYRWZwcHpiMHQ0UjgyR1lnTFNOOWpmZURPeGoxaTZSbloxVUtYRUxJblA0NVZVVE9iS2FvaVRBZ01CCkFBR2pVekJSTUIwR0ExVWREZ1FXQkJRWUtER0VIUU53elVOMmVhNXd6SlJZdVQyNHdEQWZCZ05WSFNNRUdEQVcKZ0JRWUtER0VIUU53elVOMmVhNXd6SlJZdVQyNHdEQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01BMEdDU3FHU0liMwpEUUVCQ3dVQUE0SUNBUUJkTC9UaWVEOHZuVms1cE1HSVRGaTJ0K0JnT3dWdUp2UnU2N2V6MGlsVHB3Wk1NdURMCkJ3UjZGekYxWGVLaHV2R2luclFnNTJDZUZUM1REQ0twUEo5QVcveEd1eWR3ODhER2NTQkRmZkhCdU9lNlF5NGwKaEY0L1pxYWw2eEhMZ3lMVlFJQzFsTG5MMDhoeno0Z3d5djhUblJRVm93N0VtaFQyWWYyTGNhTjBnUEdkVFAwUwpNSjllM3U1OWdKYnZhNWU3eVhOL1QzeFp1M1VXdzhiRTdBeVVCcW1acEtxQncyRXJUbWpnTmpaUEVpeHhWQ3BrCkhWMlZWSGdqK0RpdGZKNUhpNHdhSWZkNGxxQlNFbHIvQ2RTRkJMNXlIYldpQ3hPR1NDVTNaODRDZ3IvUXFJSVQKMUthbTZjVlJGdWYxbFV4SmpudWNPY05RRUplUGV3TDhLV2xKNWFUMGhIMjYyb0crQjNwY3VZZ3NPbVNZU0hkVAovTzVzUzc5MlgvdFFJMFk2Q05VVDNRRVo1bWVVYkhrM1orWHZ3dEJFbjZON2dwSzFHeWFjSTRaYXFvOUQ2eWI2Ci9kQTFiajl3RmozbzZXY2pYbFpKOWN0OHo1cVF4MkhleEt4N1pJQ3I2MWdrcUZCaDNKRS9LSFhLNkhRQWdmNmcKek1lN1BjV0xWV2JkdEd5MXlvR25RUDdMQ08xSGdXRGNxblBXN0doWWVweTZReXM4NnBwSEtKNGd0MGYwRXVlOAo4MExCMGJRaUZFeFpOY1NkV05Pc2pzNHlreDlMNFhnTFhidzRSNGR4dkhTTEVxYVIxZjJ3aUx6cDVCb0FZRi80ClJrdmwxS3J5Sk9GWk1MY2s5UVI2S0R0cXRYYjA5S2dxUHVPRkEydVhWbkcyQVBVMG1mRUJ5QXozc2c9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==mk@P14s
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUpRd0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQ1Mwd2dna3BBZ0VBQW9JQ0FRQ3VWWk1UTStrdVgySmIKSHZ6RDhBdWZPQlJPUmxtbjIybGZpbnV1L3RMSHdPUkZNQXhwQ0RjdmVPY1hocm1ETEdyTjFUN21hdW41UnJ0dwoyWENNeEwvdVRyckdONmRMWlpDaldtY1FFU2gyd2YyK2N0aUVpV2pnOUh3WTVCOTNSd09FRDVzcmVIaDNuQzlqCjE4UjhCenU2S0ZuREFjeXh6QVJZbWJIRG13aVBUdTg0TlR6UmlIc0FRcWJuUGp4NzZpYVIrMFYvMkhHaTNESkoKdjVUYjBqa05Ed1AvUGVtK0JhNS9xdnNCMXBaL3kzWFNUOXl6MERpVmIrRy94WDRGLzFzT3dYUUZOWnZTM3NRMQpqejBqNVdmQzcwdmR1dldpOVFSL2x6RWlUaFp3eEZDMVQ5UFFrZ2xRZVBDcThNVHJIb1JsV1hVREFubFRpeHpaClI4QkVKV2Z6RkJFbDNJcWdGS2dJMXNVSHE1WVprYk5LcW9iZllodDZFNHZFRTdHUHZLWnJsaDFmcFFtdzRqZlUKWldIdEhWUGtTNzgwWWRUNERSV1BLa3kxYWVCUjhTajNjeHgzT1FiTDdBUUwzOXVvTktkMk9pOGl4OVgyd1FYTApoVmJTclpNQjE3WEgzR2N2NGFscDd3VDM0Z0NuYm9sSkJ0R2xIRFRxWVJPNThqZmFXdUlzRkRmR2pMc29WaEw0CjZJQnVlTW1Ga3VqelZ5eXlYNjJudzRPVW1rRGx3cFpuejljQVdtZFBKbkorK2JqT1k1bHJMSFNPU3pjR3A0bW4KaTdZQjhua0M4a2Jlc1dDSHd5MUFhWndwVnBtYW1BQVFBVXFIc3A4MXhINmFjMjlMZUVmTmhtSUMwamZZMzNnegpzWTlZdWtaMmRWQ2x4Q3lKeitPVlZFem15bXFJa3dJREFRQUJBb0lDQUZHcWc4SEluUkRjblBvYm00UDhGSzJxCit4UXA3NERyRDBNeTM3cTc0Nml3aXg2QUlpZ25zWlphK0VKMG1iM0JsbXpDMnZyY2xhdHcvNGlmUzVLZDdsMG4KNDJYTWwyR0IvQTRSNE5yTmR0dWZCNHRxU0ZSWi9GZjVINU1YZGtnTmE2KzNFZFQ4MDg0UVM4RGxTRVZqckE2SwpMWFpsQnVzNUs4WUhoWmNncnBOWGdrZWQ1Tll4TFpHVEo1V0crWldBdkQzQmJDNjJDWkdsdmliL0NMQXJIQStxCmU1QmJnLzVBc2h4YlQ4ZHVLMFZGWGZXOTlLRUZSeVIxNjFaSElVQ1UvU1o5NkNneWswTG1tUnFQOWErMW5QUmIKM2ZuS1JaeG5WQXFqSEdDNkhOZ0psdGRBeEhSZG5PQm1Mek9jbzFxVENxbGhqU2R5UnJ5a204aUxUSjEvdW1BRQpZQWtZcjlaQ2pIbDNMWE9tRWJBTGRNLzFKODVhVE85bnJHdVhtYmJONjB3NGRsUTIzT3hZNDNyTm1pSkpzOUlRCm5MOW13VG5vOGNlYlJFRHpNdlpZOE80RjM2SkpyWWh0elYwZFEyVUtJSlVGMW9RbHVEeGVQNGpKNVkwOGQ5VkEKcy85OGFVSGJSVGJ5STFOYTVQUzRrSmNYU0hnc2psTXJOa2lQRGdBbXgzZFdRQ3Yybitldjg2d0U4YXhQWGY3MQo0b0Jva2NubkF2aHBMM1FQTzJ2SGd5bkZ0T2pwSStSUTVuVUdPcEhrbFFSbXdNbDNtOUZlNnNBNjgrLytsNVFJCm1udUk1UVRqUkpQRTJTUytMZnBrcTc0dEZvT0V6K2E5Um9nZTd3WE1Vc21IbEVwbEs1a01aR2pBSklGWDFlYnYKdm5hTFdzTUNBU1d2dnVYNWhFTzFBb0lCQVFDNU8rNkFMMTRESDdoWU9aWkczQmp5M1d5SWlDZEh1MTVNbzNxdQplVmlKOW03TFo5bGJQa2pHdm5kU3ZKeDRxN1BRcFFoVUxvUHpiQms2U0IzZmlnOWpZQm84UUFObDdiYmtTYWNkCkVCT1NFTTE0YzZnWGJOamtPUHFmN3luMDdnbVFGeXJBdzBGbzh1dVFNR1hhME5mQXAzckR5WlVSK0xqbXltQmsKeFZFclhlODRBdE1GZi9oazc1ckMxNkR5azBlN2JLYnZidkZGUGtQM1lKLzVIYzQzUlNVbWJHdHpwQWRmenJ3OQpXdzVjazNSWTBVeHNpSnBTbWtSRHJRTDJSZ2dEVVZtT2pWVG41V1o5MmNrWEZOSno1WThMaUZGYUlXaGxEL1JzClJ6MUlBeW0rWjRXQnBxNW91R0ZUVEVLV0Vwb1cxVnFoT24yT1RiSURzL2R1M3dJL0FvSUJBUUR3NzZFTC9VWWMKQ0hRNFN0NjgyYjBBVnhWeWhOZDYrdTBIbk1Zb1lmRmh1WXZwOGZZaDliVHV3bmQ1OWp6MkV3NFRoWGt4cGFGNwpWc3VZZ1ZZRURuNUNYQVFpOEZqWXR5MXRIR0NZUDFCbFVjYlgyOHFqVEpHUnhSa3AxQzlvRnFwSXZDQnZDcEMyCk44Mldyek52NFRvaFJQV0NObmVzRm44am9MUDRPQWEwWWh4bWVETlZPK0IwaHVLbG5CNGU5TTlQWU8yN1o3cW0Kbk5jVThDUmlHZlQzK1hDVmJFY1BWeGhzTURhRkx6K3RrMXFqUjh3alBUanA4Z0pUbEIwcnRUWTZWeEYrS1dTSApBYksxaStMdXUzTUFuZ3YrMko0R2dzaTlQRDhnRzgzV0k2MnNBUDV0R1FSVythNnFlN29LNk5QY3lhSHJDV0JYCk52QkhNdlhJZ1B5dEFvSUJBUUN2dnZFV3BkcG8xRnV2T1ZRZmZ3d2N3WUVNT1VJcmlOWjdtRS81NGgvakpmRVIKQkVMeGt6S3hmbHp3SHd2R1lnS0ZYMDk3cjNaNktvSDFEaDlwekMrMWRhVHVyVDJNSS9KMnZuclQxRUQ5UVB2eAo0S29ITDdySkxsWjhFQXFhM0k0dUxBemdQMkY4Rlo3eWV6am9WMldjNEVwV0lKaFRLTTBtQzdWUlp2VVFWRnQzCnBSWmFEWVM3SDZxU1dzdlYyMjhmb0lMeWdTeGhLaWFLT3g4TTJQNmk2ZlBKZE95dUYxNzN3OHBOM0dyUDR3ZHMKallnWkliSnAxUHdYeWJzWnRuQTcxWjlHNVVrOWpDV21Hay8wbWtqaXRWYjI5aXRaZklEMEFpTkI2SVY0SWFnbApnMHJrTENVbUxtb0pBajNhN1dOTmJyaENhS0JmdDgvQ082bnpnNXM1QW9JQkFRRHBVM2NIOEZnMEQ2L1ZVQlJTCm1SNml0TEx0ZTE1ZUY2RHlUVTNOajhRK0duMDNxdjNzdDFGb0kyV204K0xuZjE2VFl5QVNCMC9SN1NVdjVKalQKUnVIWkM5bHBxSTZ5R1ByaC9xaEE2SmZIOXlEMHJFS2FVQzF0R0k0YzV3S2Q3ODBxc1IxTHk5U0cwcFhEaHBudQprQlJHWWN6TU5FbENtMnEycXd0K3Aycyt4d0N2NzFudkFoU0ZaSmNiUUl3ZStIL0haSnYxY0NmZThHYU9QVjFPCnI4cC9WczVEdGw4K3FON2E3dm50a3VzOUFrVzFlSE5sOFFVcjhoVjBzU3hxeG92a2hhdElIWGZnRXJIcGhMWFkKOGlrV0FQaW03VXBrRGNXdkZTZ2d4U3hhWTZUdHZPeW41S0ZDUlh4MFYydTg0dXRCbHZhNmNoTWRndlBBVDhhYwpUT1hsQW9JQkFCM0VjZnhPRHo2U2NsMmV3TWF2UngyQTJ0ZCt2UmJSVVVPcmVqUmE2R1E3NHg4S0I2QzF2cDFICkg5N29ZdDdoM3ZSRGxRSzMySm41L0VROFFJbWJ4RGxHYXZRQitmZ2lMelBVVTg5UEs2LzhRdnBsQ0lGYkVha1gKeURWNjJMRWJxdHRlK2E3Z0l5bG5QQmt3bTJuSWdkUGt6Y2orMTVHb3NnWWUxQ1h6c0dnVU1oU3RpaTJYQXlGOAp5clNxTFlYWlNsc3czbUNxUDJ6VU95dEo2WGJiUWpYa2VZb3BXNlZPdXBpTUpYRVNEWmVIVkRadzUzeTdlNTNmCm5qeXdsa2YrZzhhOGI5U3VmNVhGdGpaRmpYVm5hdWdIK1FzYXJyempsb0x5dnl1M0NHeWFLc25HbFZHN01OZGsKdVhiMU5qdU8wVHNlSTdQc21melJpSTZPMTZ4RStZdz0KLS0tLS1FTkQgUFJJVkFURSBLRVktLS0tLQo=mk@P14s
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ssl-issuer
  namespace: demoreqrespj
spec:
  ca:
    secretName: demoreqrespj-tls-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demoreqrespj-deploy
  namespace: demoreqrespj
spec:
  replicas: 4
  selector:
    matchLabels: 
      app: demoreqrespj
  template:
    metadata:
      labels:
        app: demoreqrespj
    spec:
      containers:
      - name: demoreqrespj
        image: mkubik/demoreqrespj:0.1.0
        ports:
        - name: web
          containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: demoreqrespj-svc
  namespace: demoreqrespj
  labels:
    app: demoreqrespj
spec:
  type: ClusterIP
  ports:
  - name:  http
    port:  8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: demoreqrespj
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demoreqrespj-ingress
  namespace: demoreqrespj
spec:
  rules:
  - host: "demoreqrespj.kube-demo-1.kubik.home"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: app-test-1-svc 
            port:
              number: 80
  tls:
  - hosts:
    - demoreqrespj.kube-demo-1.kubik.home
    secretName: demoreqrespj-tls-secret              
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: demoreqrespj-cert
  namespace: demoreqrespj
spec:
  secretName: demoreqrespj-tls-secret
  issuerRef:
    name: ssl-issuer
    kind: ClusterIssuer
  dnsNames:
    - demoreqrespj.kube-demo-1.kubik.home
